#!/bin/sh
LANG=C
if [ $# -lt 1 ]; then
    echo "usage : $0  log2(N)  [repeat]"
    exit
fi
log2N=$1; shift     # log2(N)
if [ $log2N -lt 12 ]; then log2N=12; fi
if [ $# -gt 0 ]; then
    repeat=$1; shift
    if [ $repeat -le 0 ]; then repeat=1; fi
fi
rm -f tmp[1-9]*

sed -i -e '1,/^@/!d' $0     # Delete data part
echo "start    : `date -u`" >> $0       # add date
echo "computer : `uname -norpv`" >> $0
echo "operator : `id -un`" >> $0
echo "option   : $log2N ${repeat:=1}" >> $0

for i in `seq 1 $repeat`; do echo "$0:$i `date`" > /dev/stderr
    random.awk `echo 2^$log2N | bc` > data
    for j in `seq 12 $log2N`; do N=`echo 2^$j | bc`; echo "$i:$j" | tee /dev/stderr
        java -jar JavaSort.jar -N $N lha data 
    done
done > tmp$$
echo "stop     : `date -u`" >> $0       # add date

OUT=tmp.`basename $0`
et.awk -v 'x=log2(N)' tmp$$ > $OUT
expand -t `col.awk $OUT` $OUT | tee -a $0
echo "Raw data is in a file tmp$$"

exit

@
